services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  grpc-server:
    build: .
    container_name: grpc_server
    env_file: .env
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - SERVER_MODE=grpc
    depends_on:
      - mysql
    ports:
      - "50051:50051"
    restart: always

  rmi-server:
    build: .
    container_name: rmi_server
    env_file: .env
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - SERVER_MODE=rmi
    depends_on:
      - mysql
    ports:
      - "1099:1099"
    restart: always

  thrift-server:
    build: .
    container_name: thrift_server
    env_file: .env
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - SERVER_MODE=thrift
    depends_on:
      - mysql
    ports:
      - "9090:9090"
    restart: always
  
volumes:
  mysql_data:
